<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Azure.Dev.Cli.Infra</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\azd.Core\azd.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.ResourceManager" Version="1.15.0" />
    <PackageReference Include="Azure.ResourceManager.Resources" Version="1.10.2" />
    <PackageReference Include="Azure.ResourceManager.AppService" Version="1.3.0" />
    <PackageReference Include="Azure.ResourceManager.AppContainers" Version="1.4.0" />
    <PackageReference Include="Azure.ResourceManager.ContainerRegistry" Version="1.3.0" />
    <PackageReference Include="Azure.ResourceManager.ContainerService" Version="1.3.0" />
    <PackageReference Include="Azure.ResourceManager.Storage" Version="1.4.2" />
    <PackageReference Include="Azure.ResourceManager.KeyVault" Version="1.4.1" />
    <PackageReference Include="Azure.ResourceManager.Sql" Version="1.5.0" />
    <PackageReference Include="Azure.ResourceManager.CosmosDB" Version="1.5.1" />
  </ItemGroup>

</Project>
