<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Azure.Dev.Cli.Auth</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\azd.Core\azd.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.66.2" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.66.2" />
  </ItemGroup>

</Project>
